/* eslint-disable import/no-extraneous-dependencies */
const withBundleAnalyzer = require("@next/bundle-analyzer")({
  enabled: process.env.ANALYZE === "true",
});

module.exports = withBundleAnalyzer({
  poweredByHeader: false,
  trailingSlash: true,
  reactStrictMode: true,

  // ✅ CORREGIDO
  basePath: "/portfolio",
  assetPrefix: "/portfolio/",

  // ✅ NECESARIO PARA GITHUB PAGES
  output: "export",

  // ✅ NECESARIO PARA IMÁGENES EN PAGES
  images: {
    unoptimized: true,
  },
});
